Repository signalwire/libks, pull requests merged in 2021-02, with the labels that each got.

#92 Do not detach worker threads in ks_thread_pool
  src/ks_thread_pool.c
Labels: enhancement

#78 Version bump Windows package to v2.0
  win/libks-version.props
Labels: enhancement

#77 Extend error handling in ks_poll on Windows. Avoid setting POLLERR and POLLHUP as they are meaningless in the events field. Setting POLLHUP on Windows results as an error 10022 (Invalid argument).
  src/ks_socket.c
Labels: bug

#80 Fix CRYPTO_MEM_CHECK_ON undefined
  src/ks_ssl.c
Labels: bug, enhancement
